### ISSUE TITLE
Trigger from pull requests broken?

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/netlify-plugin-github-dispatch#2]
```
HttpError: No ref found for: pull/1/head
No ref found for: pull/1/head

In "onSuccess" event in "netlify-plugin-github-dispatch" from netlify.toml and package.json
at /node_modules/@octokit/request/dist-node/index.js:66:23
at async dispatchWorkflow (/node_modules/netlify-plugin-github-dispatch/src/dispatch.js:38:3)
at async onSuccess (/node_modules/netlify-plugin-github-dispatch/src/index.js:36:7)
```

and the workflow is not triggered

```
11:16:54 PM: Deployed URL https://deploy-preview-1--tested-ecommerce-store.netlify.app
11:16:54 PM: [
11:16:54 PM:   {
11:16:54 PM:     id: 5789025,
11:16:54 PM:     node_id: 'MDg6V29ya2Zsb3c1Nzg5MDI1',
11:16:54 PM:     name: 'e2e',
11:16:54 PM:     path: '.github/workflows/e2e.yml',
11:16:54 PM:     state: 'active',
11:16:54 PM:     created_at: '2021-02-13T09:11:56.000-05:00',
11:16:54 PM:     updated_at: '2021-02-13T09:11:56.000-05:00',
11:16:54 PM:     url: 'https://api.github.com/repos/bahmutov/ecommerce-netlify/actions/workflows/5789025',
11:16:54 PM:     html_url: 'https://github.com/bahmutov/ecommerce-netlify/blob/main/.github/workflows/e2e.yml',
11:16:54 PM:     badge_url: 'https://github.com/bahmutov/ecommerce-netlify/workflows/e2e/badge.svg'
11:16:54 PM:   }
11:16:54 PM: ]
11:16:54 PM: triggering GitHub with {
11:16:54 PM:   owner: 'bahmutov',
11:16:54 PM:   repo: 'ecommerce-netlify',
11:16:54 PM:   workflow_id: '.github/workflows/e2e.yml',
11:16:54 PM:   ref: 'pull/1/head',
11:16:54 PM:   inputs: {
11:16:54 PM:     siteName: 'tested-ecommerce-store',
11:16:54 PM:     deployPrimeUrl: 'https://deploy-preview-1--tested-ecommerce-store.netlify.app'
11:16:54 PM:   }
11:16:54 PM: }
11:16:54 PM: ​
11:16:54 PM: ────────────────────────────────────────────────────────────────
11:16:54 PM:   Plugin "netlify-plugin-github-dispatch" failed                
11:16:54 PM: ────────────────────────────────────────────────────────────────
11:16:54 PM: ​
11:16:54 PM:   Error message
11:16:54 PM:   HttpError: No ref found for: pull/1/head
11:16:54 PM:   No ref found for: pull/1/head
11:16:54 PM: ​
11:16:54 PM:   Plugin details
11:16:54 PM:   Package:        netlify-plugin-github-dispatch
11:16:54 PM:   Version:        1.0.0
11:16:54 PM:   Repository:     git+https://github.com/bahmutov/netlify-plugin-github-dispatch.git
11:16:54 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-github-dispatch
11:16:54 PM:   Report issues:  https://github.com/bahmutov/netlify-plugin-github-dispatch/issues
11:16:54 PM: ​
11:16:54 PM:   Error location
11:16:54 PM:   In "onSuccess" event in "netlify-plugin-github-dispatch" from netlify.toml and package.json
11:16:54 PM:       at /node_modules/@octokit/request/dist-node/index.js:66:23
11:16:54 PM:       at async dispatchWorkflow (/node_modules/netlify-plugin-github-dispatch/src/dispatch.js:38:3)
11:16:54 PM:       at async onSuccess (/node_modules/netlify-plugin-github-dispatch/src/index.js:36:7)
11:16:54 PM: ​
```

**Comment by gauravprasadgp** [comment]
Hi @bahmutov i am still getting this error, on 1.1.0.  i even tried using v1.0.2/ v1.0.3 no luck

**Comment by bahmutov** [comment]
Well you could try debugging the problem

**Comment by gauravprasadgp** [comment]
Thanks for the reply. Yeah, currently I am trying to debug it, seems something wrong with octokit request. If you have any idea how you got it fixed will be of great help, since it has started to reappear.
