### ISSUE TITLE
Error: function () { [native code] } could not be cloned.

### ISSUE THREAD

**Issue by bennymeade** [bahmutov/netlify-plugin-github-dispatch#5]
Hi @bahmutov this plugin is exactly what we need.

The first error I came across after following your steps was:
```
8:32:52 AM:   Configuration error                                           
8:32:52 AM: ────────────────────────────────────────────────────────────────
8:32:52 AM: ​
8:32:52 AM:   Error message
8:32:52 AM:   Plugins must be installed either in the Netlify App or in "package.json".
8:32:52 AM:   Please run "npm install -D netlify-plugin-github-dispatch" or "yarn add -D netlify-plugin-github-dispatch".
```
So I did as the message suggests and ran `npm install -D netlify-plugin-github-dispatch`.

Then I can get further and the Netlify Deploy log returns this message from this plugin:
![image](https://user-images.githubusercontent.com/1033474/147264195-11286cd7-6d41-4ae5-92db-b885d5360733.png)

But the logs then show a second error, which I'm stuck on is:
```
8:35:32 AM:   Plugin "netlify-plugin-github-dispatch" internal error        
8:35:32 AM: ────────────────────────────────────────────────────────────────
8:35:32 AM: ​
8:35:32 AM:   Error message
8:35:32 AM:   Error: function () { [native code] } could not be cloned.
8:35:32 AM: ​
8:35:32 AM:   Plugin details
8:35:32 AM:   Package:        netlify-plugin-github-dispatch
8:35:32 AM:   Version:        1.1.0
8:35:32 AM:   Repository:     git+https://github.com/bahmutov/netlify-plugin-github-dispatch.git
8:35:32 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-github-dispatch
8:35:32 AM:   Report issues:  https://github.com/bahmutov/netlify-plugin-github-dispatch/issues
8:35:32 AM: ​
8:35:32 AM:   Error location
8:35:32 AM:   In "onSuccess" event in "netlify-plugin-github-dispatch" from netlify.toml and package.json
8:35:32 AM:       at writeChannelMessage (internal/child_process/serialization.js:82:9)
8:35:32 AM:       at process.target._send (internal/child_process.js:814:17)
8:35:32 AM:       at process.target.send (internal/child_process.js:712:19)
8:35:32 AM:       at internal/util.js:340:30
8:35:32 AM:       at new Promise (<anonymous>)
8:35:32 AM:       at bound  (internal/util.js:339:12)
8:35:32 AM:       at sendEventToParent (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/ipc.js:123:46)
8:35:32 AM:       at handleError (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/error.js:13:9)
8:35:32 AM:       at handleEvent (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/main.js:45:11)
8:35:32 AM:       at processTicksAndRejections (internal/process/task_queues.js:95:5)
8:35:32 AM: ​
8:35:32 AM:   Resolved config
8:35:32 AM:   build:
8:35:32 AM:     base: /opt/build/repo/packages/website
8:35:32 AM:     command: npm run deploy
8:35:32 AM:     commandOrigin: ui
8:35:32 AM:     environment:
8:35:32 AM:       - GITHUB_TOKEN
8:35:32 AM:       - NODE_VERSION
8:35:32 AM:       - SANITY_DATASET
8:35:32 AM:       - SANITY_PROJECTID
8:35:32 AM:       - SANITY_TOKEN
8:35:32 AM:     publish: /opt/build/repo/packages/website/fakedist
8:35:32 AM:     publishOrigin: ui
8:35:32 AM:   functionsDirectory: /opt/build/repo/packages/website/functions
8:35:32 AM:   plugins:
8:35:32 AM:     - inputs: {}
8:35:32 AM:       origin: config
8:35:32 AM:       package: netlify-plugin-github-dispatch
8:35:32 AM:   redirects:
8:35:32 AM:     - force: true
8:35:32 AM:       from: /pdf/*
      status: 200
      to: /.netlify/functions/file/:splat
```

After this the Netlify Build Completes but my GH Actions workflow is not triggered.

**Comment by bahmutov** [comment]
This is weird, never seen this error before. Will look into when I have time

**Comment by bennymeade** [comment]
Thanks. Let me know if you need more info from me. Here's my `netlify.toml` file:

![image](https://user-images.githubusercontent.com/1033474/147293348-80b01186-c4b3-468b-a4e5-9e2bf3603ea2.png)

Package version: ```"netlify-plugin-github-dispatch": "1.1.0"```

**Comment by bennymeade** [comment]
@bahmutov my previous test was based on my colleagues mono-repo Netlify site configuration so I decided to start from stratch on a new repo. I installed a boilerplate Netlify site and carried out all of your setup steps. 

Noting that I was still prompted to `npm i` your package `npm install -D netlify-plugin-github-dispatch`, everything worked smoothly and a successful Netlify build triggered my GH Actions workflow.

I will need to understand the difference between our project mono-repo (which errors) and the boilerplate project (no errors), before I can use this package in our corporate environment.

![image](https://user-images.githubusercontent.com/1033474/147851374-fa6cc946-2ea5-487b-8d35-18945df2e78b.png)

**Comment by sirpeas** [comment]
@bahmutov got same issue and from mono-repo as well. I am trying to dispatch event from mono repo through netlify to another repository

**Comment by bennymeade** [comment]
@bahmutov I tried this plugin again on a new slim mono-repo and the error does occur. I originally thought it was because of our company's previous massive mono-repo, but now I see it in any mono-repo config:

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/1033474/176678845-fe281d3a-60cb-4f7f-ade9-73a825df73a9.png">



```
12:28:35 PM: ────────────────────────────────────────────────────────────────
12:28:35 PM:   Plugin "netlify-plugin-github-dispatch" internal error        
12:28:35 PM: ────────────────────────────────────────────────────────────────
12:28:35 PM: ​
12:28:35 PM:   Error message
12:28:35 PM:   Error: function () { [native code] } could not be cloned.
12:28:35 PM: ​
12:28:35 PM:   Plugin details
12:28:35 PM:   Package:        netlify-plugin-github-dispatch
12:28:35 PM:   Version:        1.1.0
12:28:35 PM:   Repository:     git+https://github.com/bahmutov/netlify-plugin-github-dispatch.git
12:28:35 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-github-dispatch
12:28:35 PM:   Report issues:  https://github.com/bahmutov/netlify-plugin-github-dispatch/issues
12:28:35 PM: ​
12:28:35 PM:   Error location
12:28:35 PM:   In "onSuccess" event in "netlify-plugin-github-dispatch" from netlify.toml and package.json
12:28:35 PM:       at writeChannelMessage (node:internal/child_process/serialization:82:9)
12:28:35 PM:       at process.target._send (node:internal/child_process:839:17)
12:28:35 PM:       at process.target.send (node:internal/child_process:739:19)
12:28:35 PM:       at node:internal/util:360:7
12:28:35 PM:       at new Promise (<anonymous>)
12:28:35 PM:       at bound  (node:internal/util:346:12)
12:28:35 PM:       at sendEventToParent (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/ipc.js:123:46)
12:28:35 PM:       at handleError (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/error.js:13:9)
12:28:35 PM:       at handleEvent (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/main.js:45:11)
12:28:35 PM:       at processTicksAndRejections (node:internal/process/task_queues:96:5)
12:28:35 PM: ​
12:28:35 PM:   Resolved config
12:28:35 PM:   build:
12:28:35 PM:     base: /opt/build/repo/packages/website
12:28:35 PM:     command: yarn build 2>&1 | tee logfile && curl --data-binary @logfile https://9x4zydorhe.execute-api.eu-west-1.amazonaws.com/dev/log/$SITE_ID/$DEPLOY_ID
12:28:35 PM:     commandOrigin: config
12:28:35 PM:     environment:
12:28:35 PM:       - GITHUB_TOKEN
12:28:35 PM:       - NETLIFY_USE_YARN
12:28:35 PM:       - NEXT_PRIVATE_TARGET
12:28:35 PM:     publish: /opt/build/repo/packages/website/.next
12:28:35 PM:     publishOrigin: config
12:28:35 PM:   functions:
12:28:35 PM:     ___netlify-handler:
12:28:35 PM:       external_node_modules: []
12:28:35 PM:       included_files:
12:28:35 PM:         - .env
12:28:35 PM:         - .env.local
12:28:35 PM:         - .env.production
12:28:35 PM:         - .env.production.local
12:28:35 PM:         - ./public/locales/**
        - ./next-i18next.config.js
        - .next/server/**
        - .next/serverless/**
        - .next/*.json
        - .next/BUILD_ID
        - .next/static/chunks/webpack-middleware*.js
        - '!.next/server/**/*.js.nft.json'
        - '!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*'
12:28:35 PM:         - '!node_modules/next/dist/server/lib/squoosh/**/*.wasm'
12:28:35 PM:         - '!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm'
12:28:35 PM:         - '!node_modules/next/dist/compiled/webpack/bundle4.js'
12:28:35 PM:         - '!node_modules/next/dist/compiled/webpack/bundle5.js'
12:28:35 PM:       node_bundler: nft
12:28:35 PM:     ___netlify-odb-handler:
12:28:35 PM:       external_node_modules: []
12:28:35 PM:       included_files:
12:28:35 PM:         - .env
12:28:35 PM:         - .env.local
12:28:35 PM:         - .env.production
12:28:35 PM:         - .env.production.local
12:28:35 PM:         - ./public/locales/**
        - ./next-i18next.config.js
        - .next/server/**
        - .next/serverless/**
        - .next/*.json
        - .next/BUILD_ID
        - .next/static/chunks/webpack-middleware*.js
        - '!.next/server/**/*.js.nft.json'
        - '!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*'
12:28:35 PM:         - '!node_modules/next/dist/server/lib/squoosh/**/*.wasm'
12:28:35 PM:         - '!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm'
12:28:35 PM:         - '!node_modules/next/dist/compiled/webpack/bundle4.js'
12:28:35 PM:         - '!node_modules/next/dist/compiled/webpack/bundle5.js'
12:28:35 PM:       node_bundler: nft
12:28:35 PM:     _ipx:
12:28:35 PM:       node_bundler: nft
12:28:35 PM:   plugins:
12:28:35 PM:     - inputs: {}
12:28:35 PM:       origin: ui
12:28:35 PM:       package: '@netlify/plugin-nextjs'
12:28:35 PM:     - inputs: {}
12:28:35 PM:       origin: config
12:28:35 PM:       package: /plugins/netlify-plugin-build-logs
12:28:35 PM:     - inputs: {}
12:28:35 PM:       origin: config
12:28:35 PM:       package: netlify-plugin-github-dispatch
12:28:35 PM:   redirects:
12:28:35 PM:     - from: /_next/static/*
      status: 200
      to: /static/:splat
    - from: /_next/image*
      query:
        q: ':quality'
        url: ':url'
        w: ':width'
      status: 301
      to: /_ipx/w_:width,q_:quality/:url
    - from: /_ipx/*
      status: 200
      to: /.netlify/builders/_ipx
    - force: true
      from: /cache/*
      status: 404
      to: /404.html
    - force: true
      from: /server/*
      status: 404
      to: /404.html
    - force: true
      from: /serverless/*
      status: 404
      to: /404.html
    - force: true
      from: /trace
      status: 404
      to: /404.html
    - force: true
      from: /traces
      status: 404
      to: /404.html
    - force: true
      from: /routes-manifest.json
      status: 404
      to: /404.html
    - force: true
      from: /build-manifest.json
      status: 404
      to: /404.html
    - force: true
      from: /prerender-manifest.json
      status: 404
      to: /404.html
    - force: true
      from: /react-loadable-manifest.json
      status: 404
      to: /404.html
    - force: true
      from: /BUILD_ID
      status: 404
      to: /404.html
    - from: /api
      status: 200
      to: /.netlify/functions/___netlify-handler
    - from: /api/*
      status: 200
      to: /.netlify/functions/___netlify-handler
    - conditions:
        Cookie:
          - __prerender_bypass
          - __next_preview_data
      from: /favicon.ico
      status: 200
      to: /favicon.ico
    - conditions:
        Cookie:
          - __prerender_bypass
          - __next_preview_data
      from: /vercel.svg
      status: 200
      to: /vercel.svg
    - conditions:
        Cookie:
          - __prerender_bypass
          - __next_preview_data
      force: true
      from: /*
      status: 200
      to: /.netlify/functions/___netlify-handler
    - from: /_next/data/GoSBdjjMfV8_2hPpQmIy2/index.json
      status: 200
      to: /.netlify/functions/___netlify-handler
    - from: /
      status: 200
      to: /.netlify/functions/___netlify-handler
    - from: /*
      status: 200
      to: /.netlify/functions/___netlify-handler
  redirectsOrigin: inline
```

**Comment by zhex900** [comment]
I have the same issue. 
Is it a Github token issue?

**Comment by bennymeade** [comment]
@bahmutov this is now working for me in a new (very tidy) mono-repo, here is the mono-repo structure:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/1033474/177408617-7eb91bfe-4895-4682-a033-e5ee69298fc8.png">

My `e2e-int-tests.yml` file:
```
name: e2e int tests
on:
  workflow_dispatch:
    inputs:
      siteName:
        description: Netlify Site Name
        required: false
      deployPrimeUrl:
        description: Deployed URL
        required: true
      commit:
        description: Original repo commit SHA
        required: false

jobs:
  show-event:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo inputs
        run: echo "Testing url ${{ github.event.inputs.deployPrimeUrl }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          cd packages/website
          yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          headless: true
          working-directory: packages/website
          command: npx --package cypress@9.7.0 cypress run
```

and `netlify.toml` file:
```
[build]
    command = "yarn build .......other private stuff......."
    publish = ".next"

[[plugins]]
  package = "netlify-plugin-github-dispatch"
  [plugins.inputs]
    owner = "Unilever"
    repo = "unilever-build-logs"
    workflow = ".github/workflows/e2e-int-tests.yml"

[[plugins]]
  package = "netlify-plugin-cypress"
```

**And success:**

<img width="987" alt="image" src="https://user-images.githubusercontent.com/1033474/177409572-16f2dcbb-772b-4a18-8bd6-806e547c9b28.png">

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/1033474/177409894-782f53d9-d5ed-4827-a65a-af8e8f47b1f1.png">

Next step I need to try again in a large client mono-repo.

@zhex900 I'm admin in this repo and created the Personal Access Token in the same way described in the README.

**Some things to note:**

- I still needed an additional step: `yarn add -D netlify-plugin-github-dispatch`
- I can make that error I originally posted occur by editing by yml file, i.e. not including all the workflow_dispatch inputs
- For example, this will cause the error:
```
name: e2e int tests
on:
  workflow_dispatch:
    inputs:
      deployPrimeUrl:
        description: Deployed URL
        required: true

jobs:
  show-event:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo "Testing url ${{ github.event.inputs.deployPrimeUrl }}"
```

**Comment by zhex900** [comment]
Sorry, still not working

`Error: function () { [native code] } could not be cloned.`

```
name: e2e
on:
  workflow_dispatch:
    inputs:
      siteName:
        description: Netlify Site Name
        required: false
      deployPrimeUrl:
        description: Deployed URL
        required: true
      commit:
        description: Original repo commit SHA
        required: false
jobs:
  show-event:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Current Git info $GITHUB_WORKFLOW $GITHUB_REF $GITHUB_SHA"
      - run: echo "Testing url ${{ github.event.inputs.deployPrimeUrl }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

      # test the deployed site using
      # https://github.com/cypress-io/github-action
      - name: Cypress run 🏃‍♀️
        uses: cypress-io/github-action@v2
        with:
          install: false
          # browser: chrome
          headless: true
          record: true
          config: baseUrl=${{ github.event.inputs.deployPrimeUrl }}
          command: yarn cypress:headless
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

```
